title: "How-To-Wiki"
description: "Ein Minimalbeispiel mit Minimal Mistakes"
baseurl: "" # bleibt leer
url: "https://DominikHirsch.github.io/How-To-Wiki"

theme: minimal-mistakes-jekyll

# Navigation aktivieren
plugins:
  - jekyll-include-cache

# Suche aktivieren
search: true
search_full_content: true

# Collections (für Seiten)
collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "Inhalt"
      toc_sticky: true
