title: "How-To-Wiki"
description: "Ein Minimalbeispiel mit Minimal Mistakes"
baseurl: ""
url: "https://DominikHirsch.github.io/How-To-Wiki"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

search: true
search_full_content: true

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_label: "Inhalt"
      toc_sticky: true
